### PR TITLE
Web/sidebar redesign

### PR DESCRIPTION
**Pull request by EddyLane**
Although this isn't 100% complete, its got to the point where I think it'd be better to get the current (working) version into master.

### CODE REVIEW

**Comment by EddyLane** [comment]
@VJftw Any idea why this is failing Travis build?

**Comment by VJftw** [comment]
@EddyLane Should be passing now :) Can get this into master asap and that'll fix the chaos on all the other branches too

**Comment by EddyLane** [comment]
Doesn't look like it has unfortunately

**Comment by VJftw** [comment]
This is the one :sweat_smile:

**Pull request merged**
